### ISSUE TITLE
Best practices?

### ISSUE THREAD

**Issue by kevinquillen** [alehkot/druphpet#15]
Assume I want to setup a new VM and new Drupal site. What would my folder structure look like?

I want the code to be on the local machine with the VM hosting the Drupal app. I also want the structure to be contained and resemble this:

```
C:\Users\Kevin\Projects
C:\Users\Kevin\Projects\site1.com\(drupal files)
C:\Users\Kevin\Projects\site2.com\(drupal files)
```

How can I achieve this? I am not quite connecting the dots in the config.yaml in regards to source and target.

Would I need a druphpet folder per project, or one VM for all? How can I do either?

**Comment by kevinquillen** [comment]
Also, how come when I run vagrant up, the box(es) don't show in VirtualBox GUI manager? And when they are running, their state is not reflected there?

I also want to be able to name the boxes appropriately as to what domain/project they pertain to.

**Comment by heyyoyo** [comment]
I see that you're on Windows, I recommend to look at my post on IDE. 
I detailed my config.yaml modifications, you will see the structure I used.
https://github.com/alehkot/druphpet/issues/10 in the last comment.

Pay attention that all my drupal projects are inside /var/web and not in /var/www like this it doesn't enter in conflict with Druphet provided tools.

**Comment by heyyoyo** [comment]
VirtualBox GUI manager could be enabled, you just have to add settings in Vagrantfile. After that you will see the boot of your linux:

config.vm.provider :virtualbox do |vb|
  vb.gui = true
end

But I dont' think we need it for Drupal development, as NFS inside Windows is really fast.

But even if VirtualBox GUI is not enabled, you should see in VirtualBox manager when the machine is loaded, with the green icon. maybe your vm is not loaded completely.

**Comment by kevinquillen** [comment]
Okay, so if I change the target from /var/www to /var/web, what does that affect? Do I just need to add a 'web' folder in the DruPHPet directory so any upstream changes don't affect it?

>But even if VirtualBox GUI is not enabled, you should see in VirtualBox manager when the machine is loaded, with the green icon. maybe your vm is not loaded completely.

Yes, this is what I don't see, despite being able to see local sites and SSH'ing in to the machine. It's odd, vagrant up on OSX shows the machines in the GUI tool as early as they are built. Perhaps it is a Windows quirk, I haven't used Windows for this in quite a long time.

**Comment by heyyoyo** [comment]
> Okay, so if I change the target from /var/www to /var/web, what does that affect? Do I just need to  add a 'web' folder in the DruPHPet directory so any upstream changes don't affect it?

Aleh Kot, uses the directory /var/www to put some opensource projects like xhprof, pimpmylog, adminer... This directory /var/www is by default shared by SAMBA(linux being the server).
To access it, we just have to go to this url \\192.168.9.10\data in windows explorer.

Because this folder is local for Linux and specially apache/php, all those web projects under /var/www are really fast.

But all reading/writing from Windows are really slow. (Like git operations, editing files, ...)

That's why I'm using a separate directory /var/web for my Drupal projects. I share this directory with NFS, but this time the server is Windows, and Linux/Apache the client. The speed of browsing my websites is not affected(even faster !), but now IDE operations are really fast because local (inside Windows).

SAMBA: /var/www -> \\192.168.9.10\data
NFS:/var/web -> C:\WEB or wherever you want inside Windows. 

I liked C:\WEB because it's short and not confusing, but you could put it under your druphpet vagrant directroy, the only revert is that you want to test the same project with another druphpet configuration you will have to duplicate it.

> Yes, this is what I don't see, despite being able to see local sites and SSH'ing in to the machine. It's odd, vagrant up on OSX shows the machines in the GUI tool as early as they are built. Perhaps it is a Windows quirk, I haven't used Windows for this in quite a long time.

I never experienced this bug. Maybe it's vagrant/virtualbox version issue. I'm using last versions of both.

**Comment by kevinquillen** [comment]
Gotcha - issue resolved.
